### ISSUE TITLE
模型问题

### ISSUE THREAD

**Issue by justin-wg** [Forairaaaaa/monica#1]
模型无论是光固化还是激光烧结，都有可能有缝，而且文中提及的激光烧结可能还更严重点，两条缝，光固化反而只有一边，能提供源文件修改吗？修改完打印验证完再分享出来

**Comment by Forairaaaaa** [comment]
骚等

**Comment by justin-wg** [comment]
静候佳音

**Comment by Forairaaaaa** [comment]
https://github.com/Forairaaaaa/monica/tree/main/Model
