### ISSUE TITLE
gif 图片播放卡顿

### ISSUE THREAD

**Issue by Huwensong** [Forairaaaaa/monica#12]
你好，我们同样使用esp32s3 + lvgl gif 库播放动画，但是动画卡顿，远没有在monica 项目中播放的 gif 动画流畅，可以分享一下monica项目中的 background.gif 文件资源嘛。

**Comment by Forairaaaaa** [comment]
[这个](https://github.com/Forairaaaaa/lv_port_pc_eclipse/tree/mooncake_v8/bin/sdcard/boot_anim)？

**Comment by Huwensong** [comment]
我们是看到这个：
![花环](https://github.com/Forairaaaaa/monica/assets/76541850/b60c6a18-bd5b-4d5e-a5cc-6c43622caa0e)
花环的动画播放很流畅，请问这个花环的动画效果是gif图嘛。
如果是，可以分享一下嘛，还是说是别的动画效果。

**Comment by Forairaaaaa** [comment]
> 我们是看到这个： ![花环](https://private-user-images.githubusercontent.com/76541850/318316172-b60c6a18-bd5b-4d5e-a5cc-6c43622caa0e.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE5Mzc1NDQsIm5iZiI6MTcxMTkzNzI0NCwicGF0aCI6Ii83NjU0MTg1MC8zMTgzMTYxNzItYjYwYzZhMTgtYmQ1Yi00ZDVlLWE1Y2MtNmM0MzYyMmNhYTBlLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDAxVDAyMDcyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk4YWQxNzNhOWFmOTg2NDdmNWUwYzQ2MjI1OTNkMzEzZjU4OTZiYWYxMDI5MTE0YmEyZTZkNjBjNWM2OGUxY2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.rUrTAXkky7oPS0bkOtCSDDGSrYejm8pRYOFMzj9eA9Q) 花环的动画播放很流畅，请问这个花环的动画效果是gif图嘛。 如果是，可以分享一下嘛，还是说是别的动画效果。

不是

**Comment by Huwensong** [comment]
是什么样的动画效果呢，mjpeg？

**Comment by Forairaaaaa** [comment]
> 是什么样的动画效果呢，mjpeg？

rgb逐帧推

**Comment by Huwensong** [comment]
ok,非常感谢

**Comment by Forairaaaaa** [comment]
> ok,非常感谢

不客气
